Repository jmpsec/osctrl, pull requests merged in 2020-02, with the labels that each got.

#34 bug: fix invalid logging method for api, default to none
  cmd/api/main.go
  docker/dockerize.sh
Labels: bug

#35 small refactor: to use struct for html layout pages
  cmd/admin/handlers-get.go
Labels: refactor

#36 Productionalize osctrl-api
  cmd/admin/handlers-get.go
  cmd/admin/handlers-post.go
  cmd/admin/templates/components/page-aside-right.html
  cmd/admin/types-templates.go
  cmd/admin/utils.go
  cmd/api/auth.go
  cmd/api/handlers-environments.go
  cmd/api/handlers-nodes.go
  cmd/api/handlers-platforms.go
  cmd/api/handlers-queries.go
  cmd/api/settings.go
  cmd/tls/db.go
  plugins/logging_dispatcher/logging.go
Labels: enhancement, osctrl-admin, osctrl-api

#39 Using custom user-agent
  utils/utils.go
Labels: enhancement

#40 Make services wait for backend
  admin/main.go
  api/main.go
  deploy/docker/api/Dockerfile
  deploy/docker/api/wait.sh
  deploy/docker/tls/Dockerfile
  deploy/docker/tls/wait.sh
  tls/main.go
Labels: enhancement, osctrl-admin, osctrl-api, osctrl-tls

#42 Compile osctrl statically
  Makefile
Labels: build, osctrl-admin, osctrl-api, osctrl-cli, osctrl-tls

#44 Fix for local query logs and better metrics
  api/handlers-environments.go
  api/handlers-nodes.go
  api/handlers-platforms.go
  api/handlers-queries.go
  api/main.go
  logging/logging.go
  tools/api_testing.py
Labels: bug, enhancement
