Repository jmpsec/osctrl, pull requests merged in 2024-07, with the labels that each got.

#441 Deprecating default environment and adding dashboard
  admin/auth.go
  admin/auth/auth.go
  admin/auth/go.mod
  admin/auth/go.sum
  admin/handlers/get.go
  admin/handlers/json-carves.go
  admin/handlers/json-logs.go
  admin/handlers/json-nodes.go
  admin/handlers/json-queries.go
  admin/handlers/json-stats.go
  admin/handlers/json-tags.go
  admin/handlers/post.go
  admin/handlers/templates.go
  admin/handlers/tokens.go
  admin/handlers/types-requests.go
  admin/handlers/types-templates.go
  admin/main.go
  admin/sessions/sessions.go
  admin/settings.go
  admin/templates/components/page-aside-left.html
  admin/templates/dashboard.html
  admin/templates/profile.html
  admin/templates/users.html
  api/handlers-carves.go
  api/handlers-environments.go
  api/handlers-login.go
  api/handlers-nodes.go
  api/handlers-platforms.go
  api/handlers-queries.go
  api/handlers-settings.go
  api/handlers-tags.go
  api/handlers-users.go
  api/handlers.go
  api/settings.go
  api/utils.go
  cli/node.go
  cli/permission.go
  cli/settings.go
  cli/user.go
  settings/settings.go
  tls/settings.go
  tls/utils.go
  users/go.sum
  users/permissions.go
  users/permissions_test.go
  users/users.go
  users/users_test.go
Labels: ✨ enhancement, osctrl-admin

#443 Support for osquery 5.12.1
  .env.example
  .github/workflows/build_and_test_main_merge.yml
  .github/workflows/build_and_test_pr.yml
  .github/workflows/create_tagged_releases.yml
  deploy/cicd/deb/generate-deb-package.sh
  deploy/docker/conf/dev/.env.example
  deploy/docker/dockerfiles/Dockerfile-osquery
  deploy/osquery/data/5.12.1.json
  deploy/provision.sh
  version/version.go
  version/version_test.go
Labels: osquery

#444 Dependencies update before new release
  .github/workflows/build_and_test_pr.yml
  admin/handlers/go.mod
  admin/handlers/go.sum
  admin/sessions/go.mod
  admin/sessions/go.sum
  backend/go.mod
  backend/go.sum
  cache/go.mod
  cache/go.sum
  carves/go.mod
  carves/go.sum
  environments/go.mod
  environments/go.sum
  go.mod
  go.sum
  metrics/go.mod
  metrics/go.sum
  nodes/go.mod
  nodes/go.sum
  queries/go.mod
  queries/go.sum
  settings/go.mod
  settings/go.sum
  tags/go.mod
  tags/go.sum
  tls/handlers/go.mod
  tls/handlers/go.sum
  types/go.mod
  types/go.sum
  users/go.mod
  users/go.sum
  version/go.mod
  version/go.sum
Labels: dependencies

#445 Cleanup for default env code
  admin/static/js/users.js
  cli/user.go
  deploy/provision.sh
Labels: 🧹 cleanup

#446 Adding eviction policy to redis to avoid OOM issues
  deploy/redis/redis.conf
Labels: ✨ enhancement, backend, cache

#447 Removing vagrant environment files
  .gitignore
  Makefile
  README.md
  Vagrantfile
  tools/README.md
  tools/vagrant_tmux.sh
Labels: deployment, 🧹 cleanup

#448 More dependencies update before new release
  admin/handlers/go.mod
  admin/handlers/go.sum
  admin/sessions/go.mod
  backend/go.mod
  backend/go.sum
  cache/go.mod
  cache/go.sum
  carves/go.mod
  carves/go.sum
  environments/go.mod
  go.mod
  go.sum
  logging/go.mod
  logging/go.sum
  logging/process.go
  metrics/go.mod
  metrics/go.sum
  queries/go.mod
  settings/go.mod
  tags/go.mod
  tls/handlers/go.mod
  tls/handlers/go.sum
  types/go.mod
  users/go.mod
Labels: dependencies

#449 Missing query results and `osctrl-admin` panics
  admin/handlers/json-logs.go
  admin/handlers/templates.go
  admin/handlers/types-templates.go
  admin/handlers/utils.go
  admin/templates/node.html
  admin/templates/queries-logs.html
  cache/cache.go
  settings/settings.go
Labels: osctrl-admin, :file_cabinet: logging, 🚧 bugfix, cache

#451 Small changes to docker files and air configuration
  admin/templates/queries-logs.html
  deploy/docker/conf/dev/air/.air-osctrl-admin.toml
  deploy/docker/conf/dev/air/.air-osctrl-api.toml
  deploy/docker/conf/dev/air/.air-osctrl-cli.toml
  deploy/docker/conf/dev/air/.air-osctrl-tls.toml
  deploy/docker/dockerfiles/Dockerfile-dev-admin
  deploy/docker/dockerfiles/Dockerfile-dev-cli
Labels: deployment, 📦 build

#453 Some references left to be bumped for new release
  CHANGELOG.md
  admin/handlers/go.mod
  admin/sessions/go.mod
  cache/go.mod
  cache/go.sum
  carves/go.mod
  carves/go.sum
  environments/go.mod
  go.mod
  logging/go.mod
  metrics/go.mod
  metrics/go.sum
  settings/go.mod
  tls/handlers/go.mod
  types/go.mod
  users/go.mod
  users/go.sum
Labels: 🔖 new version

#454 Logger for docker environment is set to db
  admin/handlers/handlers.go
  admin/main.go
  deploy/docker/dockerfiles/Dockerfile-dev-admin
  deploy/docker/dockerfiles/Dockerfile-dev-api
  deploy/docker/dockerfiles/Dockerfile-dev-tls
  docker-compose-dev.yml
  logging/logging.go
  tls/main.go
Labels: deployment, osctrl-tls, osctrl-admin, backend

#456 Using session key for docker dev `osctrl-admin`
  .env.example
  docker-compose-dev.yml
Labels: ✨ enhancement, osctrl-admin, dev env 🛠️

#457 Bump to dependencies after release
  admin/handlers/go.mod
  admin/handlers/go.sum
  admin/sessions/go.mod
  admin/sessions/go.sum
  backend/go.mod
  backend/go.sum
  cache/go.mod
  cache/go.sum
  carves/go.mod
  carves/go.sum
  environments/go.mod
  go.mod
  go.sum
  logging/go.mod
  logging/go.sum
  metrics/go.mod
  metrics/go.sum
  queries/go.mod
  settings/go.mod
  tags/go.mod
  tls/handlers/go.mod
  tls/handlers/go.sum
  types/go.mod
Labels: dependencies

#458 Add missing remove.sh & remove.ps1 from OSCTRL NGINX conf
  deploy/docker/conf/nginx/osctrl.conf
Labels: ✨ enhancement, dev env 🛠️

#460 Fix for enrollment one-liner using dpkg in darwin
  environments/go.sum
  environments/scripts.go
Labels: osctrl-tls, enrollment, 🚧 bugfix

#461 Changes to go.mod files and updated dependencies
  admin/handlers/go.mod
  admin/handlers/go.sum
  admin/sessions/go.mod
  admin/sessions/go.sum
  api/handlers/go.mod
  backend/go.mod
  backend/go.sum
  cache/go.mod
  cache/go.sum
  carves/go.mod
  carves/go.sum
  environments/go.mod
  environments/go.sum
  go.mod
  go.sum
  logging/go.mod
  logging/go.sum
  metrics/go.mod
  metrics/go.sum
  nodes/go.mod
  nodes/go.sum
  queries/go.mod
  queries/go.sum
  settings/go.mod
  settings/go.sum
  tags/go.mod
  tags/go.sum
  tls/handlers/go.mod
  tls/handlers/go.sum
  types/go.mod
  types/go.sum
  users/go.mod
  users/go.sum
  utils/go.mod
  version/go.mod
Labels: dependencies

#462 Having custom deb, rpm, pkg and msi packages to enroll nodes
  admin/handlers/get.go
  admin/handlers/post.go
  admin/handlers/templates.go
  admin/handlers/types-requests.go
  admin/handlers/types-templates.go
  admin/static/css/custom.css
  admin/static/js/enrolls.js
  admin/templates/enroll.html
  cli/environment.go
  cli/main.go
  deploy/docker/dockerfiles/Dockerfile-dev-cli
  environments/environments.go
  environments/util.go
  settings/settings.go
  tls/handlers/handlers.go
  tls/handlers/utils.go
  tls/handlers/utils_test.go
  tls/main.go
  utils/http-utils.go
  utils/http-utils_test.go
  utils/string-utils_test.go
Labels: osctrl-tls, osctrl-admin, osctrl-cli, enrollment

#463 Rebuilding single services in docker environment
  Makefile
Labels: ✨ enhancement, 📦 build, dev env 🛠️

#464 Adding buttons to download secret, cert and flags
  admin/handlers/templates.go
  admin/handlers/utils.go
  admin/main.go
  admin/templates/enroll.html
  settings/settings.go
Labels: ✨ enhancement, osctrl-admin

#465 Small changes to the enroll.html template
  admin/templates/enroll.html
Labels: osctrl-admin

#467 Script to repack osquery DEB packages including osctrl files (flags, secret, cert)
  tools/README.md
  tools/build-osctrl-deb.sh
  tools/git-release.sh
  tools/packages/linux/osquery.flags
  tools/packages/linux/osquery.secret
  tools/packages/linux/postinst
  tools/packages/linux/preinst
  tools/packages/osctrl-deb.sh
  tools/packages/osctrl-packager.sh
  tools/packages/osx/osquery.flags
  tools/packages/osx/osquery.secret
  tools/packages/osx/postinstall
  tools/packages/osx/preinstall
Labels: 🧹 cleanup, 🛠️ tools
